config/routes.rb
Rails.application.routes.draw do
  root 'tweets#main'
  resources :tweets
  resources :users
  resources :likes
  get 'get_image/:id', to: 'tweets#get_image'
  post 'users/login'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    validates :message , presence: true
    validates :message, length: { maximum: 140 }
    has_many :likes, dependent: :destroy
    has_many :like_users, through: :likes, source: :user
    
    def like(user)
        likes.create(user_id: user.id)
    end
    
    def unlike(user)
        likes.find_by(user_id: user.id).destroy
    end
    
    def liked?(user) #いいね済みか調べる(true / false)
        like_users.include?(user)
    end
end

app/models/user.rb
class User < ApplicationRecord
    validates :uid, presence:true
    validates :password, presence:true, confirmation: true
    has_many :likes, dependent: :destroy
    has_many :like_tweets, through: :likes, source: :tweet
    has_one :tweet, dependent: :destroy
    attr_accessor :password, :password_confirmation

    def password=(val)
        if val.present?
         self.pass = BCrypt::Password.create(val)
        end
        @password = val
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def current_user
        if session[:login_uid]
           User.find_by(uid: session[:login_uid])
        end
    end
    helper_method :current_user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def new
        tweet = Tweet.find(params[:tweet_id])
        unless tweet.liked?(current_user)
            tweet.like(current_user)
        end
        redirect_to root_path
    end
    def destroy
        tweet = Tweet.find(params[:id])
        if tweet.liked?(current_user)
            tweet.unlike(current_user)
        end
        redirect_to root_path
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def main
    @tweets = Tweet.all
  end
  
  def new
    @tweets = Tweet.new
  end
  
  def create
    if params[:tweet][:file] == nil
      @tweets = Tweet.new(message: params[:tweet][:message], tdate: Time.current, file: nil)
      @tweets.user = User.find_by(uid: session[:login_uid])
    else
      @tweets = Tweet.new(message: params[:tweet][:message], tdate: Time.current, file: params[:tweet][:file].read)
      @tweets.user = User.find_by(uid: session[:login_uid])
    end
    if @tweets.save
      flash[:notice] = "ツイートしました"
      redirect_to root_path
    else
      flash[:error] = @tweets.errors.full_messages
      render new_tweet_path
    end
  end
  
  def destroy
    tweets = Tweet.find(params[:id])
    tweets.destroy
    redirect_to root_path
  end
  
  def show
    @tweets = Tweet.find(params[:id])
  end
  
  def edit
    @tweets = Tweet.find(params[:id])
  end
  
  def ifupdate(message, tdate, file)
    if @tweets.update(message: message, tdate: tdate, file: file)
        flash[:notice] = "更新しました"
        redirect_to root_path
    else
        flash[:error] = @tweets.errors.full_messages
        redirect_to edit_tweet_path
    end
  end
  
  def update
    @tweets = Tweet.find(params[:id])
    if params[:tweet][:file] == nil
      ifupdate(params[:tweet][:message], @tweets.tdate, nil)
    else
      ifupdate(params[:tweet][:message], @tweets.tdate, params[:tweet][:file].read)
    end
  end
  
  def get_image
    image = Tweet.find(params[:id])
    send_data image.file, disposition: :inline, type:'image/png'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @users = User.new
  end
  
  def create
    @users = User.new
    if User.find_by(uid: params[:user][:uid])
      render new_user_path
      return
    end
    @user = User.new(uid: params[:user][:uid], password: params[:user][:password], password_confirmation: params[:user][:password_confirmation])
    if @user.save
      flash[:notice] = "登録しました"
      redirect_to root_path
    else
      flash[:error] = @user.errors.full_messages
      render new_user_path
    end
  end
  
  def login
    if a = User.find_by(uid: params[:uid])
        if BCrypt::Password.new(a.pass) == params[:pass]
            session[:login_uid] = params[:uid]
            redirect_to root_path
        else
            render users_login_path
        end
    else
        render users_login_path
    end
  end
  
  def show
    render "login"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="container">
      <div id="header">
        <%= render "header" %>
      </div>
      <div id="sidebar">
        <%= render "sidebar" %>
      </div>
      <div id="content">
        <%= yield %>
      </div>
      <div id="footer">
        <%= render "footer" %>
      </div>
    </div>
  </body>
</html>

app/views/tweets/_"create_and_edit".html.erb
<% if flash[:error].present? %>
<h3>エラーがあります。</h3>
<ul>
    <% flash[:error].each do |msg| %>
      <li><%= msg %></li>
    <% end %>
</ul>
<% end %>
<%= form_for @tweets , url: {action: actionname } do |f| %>
    <%= f.label :message, 'メッセージ' %>
    <%= f.text_field :message %>
    <p><%= f.label :file, 'ファイル' %>
    <%= f.file_field :file%></p>
    <%= f.submit '決定' %>
<% end %>

app/views/tweets/_create.html.erb
<% if error.present? %>
<h3>エラーがあります。</h3>
<ul>
    <% error.each do |msg| %>
      <li><%= msg %></li>
     <% end %>
</ul>
<% end %>
<%= form_for @tweets , url: {action: actionname } do |f| %>
    <%= f.label :message, 'メッセージ' %>
    <%= f.text_field :message %>
    <p><%= f.label :file, 'ファイル' %>
    <%= f.file_field :file%></p>
    <%= f.submit '決定' %>
<% end %>

app/views/tweets/_create_and_edit.html.erb
<% if flash[:error].present? %>
<h3>エラーがあります。</h3>
<ul>
    <% flash[:error].each do |msg| %>
      <li><%= msg %></li>
    <% end %>
</ul>
<% end %>
<%= form_for @tweets , url: {action: actionname } do |f| %>
    <%= f.label :message, 'メッセージ' %>
    <%= f.text_field :message %>
    <p><%= f.label :file, 'ファイル' %>
    <%= f.file_field :file%></p>
    <%= f.submit '決定' %>
<% end %>

app/views/tweets/_footer.html.erb
<% if session[:login_uid] %>
  <p><%= link_to 'ツイートする', '/tweets/new' %></p>
 <% end %>

app/views/tweets/_header.html.erb
ツイート　　　ツイートと返信　　　メディア　　　いいね　　　
<% if session[:login_uid] %>
<% else %>
  <%= link_to 'ログイン', '/users/login' %>
<% end %>

app/views/tweets/_sidebar.html.erb
<p>ホーム</p>
<p>話題を検索</p>
<p>通知</p>
<p>メッセージ</p>
<p>ブックマーク</p>
<p>リスト</p>
<p>プロフィール</p>
<p>もっと見る</p>

app/views/tweets/edit.html.erb
<%= render "create_and_edit", actionname: :update %>

app/views/tweets/index.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %><br>
<% end %>
<% @tweets.each do |tweet| %>
    <%= tweet.message %><br>
    <% if tweet.file != nil %>
      <%= image_tag "/get_image/#{tweet.id}" %>
    <% end %>
    <%= ((Time.current - tweet.tdate)/60).floor %>分前
    <%= link_to '削除', "/tweets/#{tweet.id}", method: :delete %>
    <%= link_to '表示', "/tweets/#{tweet.id}" %>
    <%= link_to '編集', "/tweets/#{tweet.id}/edit" %><br>
<% end %>

app/views/tweets/main.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %><br>
<% end %>
<% @tweets.each do |tweet| %>
    <%= User.find_by(id: tweet.user_id).uid %><br>
    <%= tweet.message %><br>
    <% if tweet.file != nil %>
      <%= image_tag "/get_image/#{tweet.id}" %>
    <% end %>
    <%= ((Time.current - tweet.tdate)/60).floor %>分前
    <%= link_to '表示', "/tweets/#{tweet.id}" %>
    <% if session[:login_uid] %>
    <%= link_to 'いいね', new_like_path(tweet_id: tweet.id)%>
    <%= link_to 'いいね削除', "/likes/#{tweet.id}", method: :delete %>
    <%= Like.where(tweet_id: tweet.id).count %>
    <% end %>
    <br>
<% end %>

app/views/users/_create_and_edit.html.erb
<% if flash[:error].present? %>
<h3>エラーがあります。</h3>
<ul>
    <% flash[:error].each do |msg| %>
      <li><%= msg %></li>
    <% end %>
</ul>
<% end %>
<%= form_for @tweets , url: {action: actionname } do |f| %>
    <%= f.label :message, 'メッセージ' %>
    <%= f.text_field :message %>
    <p><%= f.label :file, 'ファイル' %>
    <%= f.file_field :file%></p>
    <%= f.submit '決定' %>
<% end %>

app/views/users/_footer.html.erb
<% if session[:login_uid] %>
  <p><%= link_to 'ツイートする', '/tweets/new' %></p>
 <% end %>

app/views/users/_header.html.erb
ツイート　　　ツイートと返信　　　メディア　　　いいね　　　
<% if session[:login_uid] %>
<% else %>
  <%= link_to 'ログイン', '/users/login' %>
<% end %>

app/views/users/_sidebar.html.erb
<p>ホーム</p>
<p>話題を検索</p>
<p>通知</p>
<p>メッセージ</p>
<p>ブックマーク</p>
<p>リスト</p>
<p>プロフィール</p>
<p>もっと見る</p>

app/views/users/login.html.erb
<%= form_tag '/users/login', method: :post do %>
    <%= label_tag :uid, 'ユーザー名' %>
    <%= text_field_tag :uid %>
    <p><%= label_tag :pass, 'パスワード' %>
    <%= password_field_tag :pass %></p>
    <%= submit_tag '登録' %>
<% end %><br>
<%= link_to '新規登録', '/users/new' %>

app/views/users/new.html.erb
<% if flash[:error].present? %>
<h3>エラーがあります。</h3>
<ul>
    <% flash[:error].each do |msg| %>
      <li><%= msg %></li>
    <% end %>
</ul>
<% end %>
<%= form_for @users , url: {action: :create } do |f| %>
    <%= f.label :uid, 'ユーザー名' %>
    <%= f.text_field :uid %>
    <p><%= f.label :password, 'パスワード' %>
    <%= f.password_field :password %></p>
    <p>
    <%= f.label :password_confirmation, 'パスワード(確認)' %>
    <%= f.password_field :password_confirmation %>
    </p>
    <%= f.submit '決定' %>
<% end %>